title: "PyCon GR Presentation Links"
description: "Links and resources for the talk."
# For project pages:
# url: "https://YOUR_USERNAME.github.io"
# baseurl: "/presentation-links"

# Custom layout overrides theme header/footer - CSS included directly
