title: "PyCon GR Presentation Links"
description: "Links and resources for the talk."
# For project pages:
url: "https://szokeasaurusrex.github.io"
baseurl: "/pycon-gr-25-links"
# Custom layout overrides theme header/footer - CSS included directly
