title: "Swiss Python Summit Presentation Links"
description: "Links and resources for the talk."
# For project pages:
url: "https://szokeasaurusrex.github.io"
baseurl: "/swiss-python-summit-25-links"
# Custom layout overrides theme header/footer - CSS included directly
